---
- name: install Hadoop
  hosts: "hadoop-slave1,hadoop-slave2"
  become: yes
  become_user: root

  tasks:
    - name: download JDK8
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
        dest: /tmp/jdk-8u131-linux-x64.rpm
        mode: 0644
        validate_certs: no
        headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    - name: be sure JDK8 is installed
      yum:
        name: /tmp/jdk-8u131-linux-x64.rpm
        state: present      

    - name: CDH5
      get_url:
        url: https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
        dest: /etc/yum.repos.d/cloudera-cdh5.repo
    - name: RPM key
      rpm_key:
        state: present
        key: https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera

    - name: yum clean
      shell: yum clean all
    - name: Node Manager host
      yum:
        name: hadoop-yarn-nodemanager
        state: latest
    - name: NameNode host
      yum:
        name: hadoop-hdfs-datanode
        state: latest
    - name: MR history server
      yum:
        name: hadoop-mapreduce
        state: latest
