---
- name: install Hadoop
  hosts: hadoop-master
  become: yes
  become_user: root

  tasks:
    - include: hadoop-common.yml

    - name: format namenode
      expect:
        command: 'sudo -u hdfs hdfs namenode -format'
        responses:
          'Re-format filesystem in Storage Directory': 'Y'
    - name: start namenode
      service:
        name: hadoop-hdfs-namenode
        state: started

    - name: prepare directories on HDFS
      command: '{{ item }}'
      with_items:
        - 'sudo -u hdfs hadoop fs -mkdir -p /user/history'
        - 'sudo -u hdfs hadoop fs -chmod -R 1777 /user/history'
        - 'sudo -u hdfs hadoop fs -chown mapred:hadoop /user/history'
        - 'sudo -u hdfs hadoop fs -mkdir -p /var/log/hadoop-yarn'
        - 'sudo -u hdfs hadoop fs -chown yarn:mapred /var/log/hadoop-yarn'

    - name: start resouce manager
      service:
        name: hadoop-yarn-resourcemanager
        state: started

    - name: start history server
      service:
        name: hadoop-mapreduce-historyserver
        state: started
