---
- name: install Hadoop
  hosts: hadoop-master
  become: yes
  become_user: root

  tasks:
    - name: epel-release
      yum:
        name: epel-release
        state: latest
    - name: Install python-pip
      yum:
        name: python-pip
        state: latest
    - name: Install pexpect
      command: 'pip install pexpect'
    - name: download JDK8
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
        dest: /tmp/jdk-8u131-linux-x64.rpm
        mode: 0644
        validate_certs: no
        headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    - name: be sure JDK8 is installed
      yum:
        name: /tmp/jdk-8u131-linux-x64.rpm
        state: present      

    - name: CDH5
      get_url:
        url: https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo
        dest: /etc/yum.repos.d/cloudera-cdh5.repo
    - name: RPM key
      rpm_key:
        state: present
        key: https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera
    - name: yum clean
      shell: yum clean all
    - name: Install libs via yum (latest)
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - 'hadoop-yarn-resourcemanager'
        - 'hadoop-hdfs-namenode'
        - 'hadoop-mapreduce-historyserver'
        - 'hadoop-yarn-proxyserver'

    - name: remove configuration from core-site.xml
      lineinfile:
        path: /etc/hadoop/conf/core-site.xml
        regexp: '{{ item }}'
        state: absent
      with_items:
        - '^<configuration>'
        - '^</configuration>'
    - name: add property to core-site.xml
      lineinfile:
        path: /etc/hadoop/conf/core-site.xml
        line: "<configuration><property><name>fs.defaultFS</name><value>hdfs://master:8020</value></property></configuration>"
        state: present
    - name: remove </configuration>  in hdfs-site.xml
      lineinfile:
        path: /etc/hadoop/conf/hdfs-site.xml
        regexp: '{{ item }}'
        state: absent
      with_items:
        - '^<configuration>'
        - '^</configuration>'
        - '<property.*'
        - '</property>'
        - '<name.*'
        - '</name>'
        - '<value.*'
        - '</value>'
    - name: add property to hdfs-site.xml
      lineinfile:
        path: /etc/hadoop/conf/hdfs-site.xml
        line: "<configuration><property><name>dfs.permissions.superusergroup</name><value>hadoop</value></property><property><name>dfs.namenode.name.dir</name><value>/var/lib/hadoop-hdfs/cache/dfs/name</value></property><property><name>dfs.datanode.name.dir</name><value>/var/lib/hadoop-hdfs/cache/dfs/data</value></property></configuration>"
        state: present

    - name: prepare cache directories
      command: '{{ item }}'
      with_items:
        - 'sudo mkdir -p /var/lib/hadoop-hdfs/cache/dfs/name'
        - 'sudo mkdir -p /var/lib/hadoop-hdfs/cache/dfs/data'
        - 'sudo chown hdfs:hadoop -R /var/lib/hadoop-hdfs/cache/dfs'

    - name: format namenode
      expect:
        command: 'sudo -u hdfs hdfs namenode -format'
        responses:
          'Re-format filesystem in Storage Directory': 'Y'
    - name: start namenode
      service:
        name: hadoop-hdfs-namenode
        state: started
    - name: set etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ item }}'
        state: present
      with_items:
        - '192.168.33.12 master'
        - '192.168.33.13 slave1'
        - '192.168.33.14 slave2'
