---
- name: install Hadoop
  hosts: "hadoop-slave1,hadoop-slave2"
  become: yes
  become_user: root

  tasks:
    - include: hadoop-common.yml

    - name: NameNode host
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - 'hadoop-hdfs-datanode'
        - 'hadoop-yarn-nodemanager'
        - 'hadoop-mapreduce'
  
    - name: start datanode
      service:
        name: hadoop-hdfs-datanode
        state: started
    - name: start node manager
      service:
        name: hadoop-yarn-nodemanager
        state: started
